# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_auto_20180912_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='avg_ratting',
            new_name='total_ratting',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
    ]
